In [3]:
import pandas as pd

In [137]:
data = pd.read_excel('classproject.xlsx')

In [138]:
data.drop('respid',axis=1,inplace=True)

In [141]:
data = data.apply(pd.to_numeric)

In [142]:
data.columns

Index([u'brand', u'affect_1', u'affect_2', u'affect_3', u'hedonic_1',
       u'hedonic 2', u'hedonic_3', u'hedonic 4', u'functional_1',
       u'functional_2', u'functional_3', u'functional_4'],
      dtype='object')

In [143]:
df_hedonic = data[['hedonic_1','hedonic 2','hedonic_3','hedonic 4']]

In [144]:
df_functional = data[['functional_1','functional_2','functional_3','functional_4']]

In [145]:
df_combined = data[['hedonic_1','hedonic 2','hedonic_3','hedonic 4','functional_1','functional_2','functional_3','functional_4']]

In [146]:
df_affect =  data[['affect_1','affect_2','affect_3']]

In [147]:
import numpy as np
from sklearn.decomposition import PCA

In [192]:
pca = PCA(n_components=8,tol=1)

pca_combined = pca.fit(df_combined)

pca_combined.explained_variance_ratio_

array([ 0.5996445 ,  0.11616797,  0.07843488,  0.057144  ,  0.04628147,
        0.04309341,  0.03792452,  0.02130925])

In [193]:
df_combined.head()

hedonic_1  hedonic 2  hedonic_3  hedonic 4  functional_1  functional_2  \
0          5          4          5          5             5             4   
1          5          5          5          5             5             4   
2          4          4          3          3             5             4   
3          4          4          3          3             4             3   
4          3          3          3          3             3             3   

   functional_3  functional_4  
0             4             5  
1             5             4  
2             3             3  
3             4             4  
4             3             3

In [194]:
pca_combined.components_

array([[-0.36997515, -0.37919153, -0.38632451, -0.34468557, -0.28605353,
        -0.31622288, -0.38041752, -0.35318037],
       [ 0.22864371,  0.28464229,  0.4731271 ,  0.24966076, -0.47000999,
        -0.11383481, -0.53349913, -0.24906223],
       [-0.25365543, -0.488044  ,  0.24141033,  0.40350752, -0.32198314,
        -0.30421236,  0.14471026,  0.50913195],
       [ 0.48962467,  0.18844735, -0.19511191, -0.12471931,  0.06157614,
        -0.79398837,  0.12672171,  0.14444437],
       [-0.49277978,  0.30748221,  0.26896723,  0.0894611 ,  0.01395131,
        -0.31480277,  0.50902573, -0.47315272],
       [-0.46054773,  0.6017535 , -0.11333458, -0.22874119, -0.13498426,
        -0.02304652, -0.21404947,  0.54410677],
       [-0.22292241,  0.01145209, -0.07472233,  0.49066892,  0.6696047 ,
        -0.21988028, -0.45394536, -0.03241702],
       [ 0.04622245,  0.21144611, -0.66316287,  0.5825859 , -0.35073264,
         0.12689673,  0.15056884, -0.11034299]])

In [195]:
pca_combined.components_[0]

array([-0.36997515, -0.37919153, -0.38632451, -0.34468557, -0.28605353,
       -0.31622288, -0.38041752, -0.35318037])

In [188]:
df_combined.head()

hedonic_1  hedonic 2  hedonic_3  hedonic 4  functional_1  functional_2  \
0          5          4          5          5             5             4   
1          5          5          5          5             5             4   
2          4          4          3          3             5             4   
3          4          4          3          3             4             3   
4          3          3          3          3             3             3   

   functional_3  functional_4  
0             4             5  
1             5             4  
2             3             3  
3             4             4  
4             3             3

In [196]:
dehalo = df_combined - df_combined * pca_combined.components_[0]

In [190]:
dehalo.head()

hedonic_1  hedonic 2  hedonic_3  hedonic 4  functional_1  functional_2  \
0   6.849876   5.516766   6.931623   6.723428      6.430268      5.264892   
1   6.849876   6.895958   6.931623   6.723428      6.430268      5.264892   
2   5.479901   5.516766   4.158974   4.034057      6.430268      5.264892   
3   5.479901   5.516766   4.158974   4.034057      5.144214      3.948669   
4   4.109925   4.137575   4.158974   4.034057      3.858161      3.948669   

   functional_3  functional_4  
0      5.521670      6.765902  
1      6.902088      5.412721  
2      4.141253      4.059541  
3      5.521670      5.412721  
4      4.141253      4.059541

In [197]:
pca_2 = PCA(n_components=3)

pca_dehalo = pca_2.fit(dehalo)

pca_dehalo.explained_variance_ratio_

array([ 0.60201414,  0.11637908,  0.0779539 ])